#!/usr/bin/env bash
#
#   - Creates the file /var/run/myscript.pid containing its PID
#   - Displays To infinity and beyond indefinitely
#   - Displays I hate the kill command when receiving a SIGTERM signal
#   - Displays Y U no love me?! when receiving a SIGINT signal
#   - Deletes the file /var/run/my.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

PRID=$$
echo "$PRID" > /var/run/myscript.pid

function Do_not_love_at_Signal()
{
    echo "Y U no love me?!"
}

function Hate_the_kill_Signal()
{
    echo "I hate the kill command"
}
function Delete_file_Signal()
{
	rm -f /var/run/my.pid
	kill -9 $PRID
}

trap Do_not_love_at_Signal SIGINT
trap Hate_the_kill_Signal SIGTERM
trap Delete_file_Signal SIGINT SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
