#!/usr/bin/env bash
# This script is displaying "Holberton School" 9 times and one time "hi" using while
i=1

while [ $i -lt "10" ]
do
    echo "Holberton School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Holberton School"
    fi

    ((i += 1))
done
